### ISSUE TITLE
Query by dates

### ISSUE THREAD

**Issue by ddow** [gtalarico/pyairtable#119]
I've been looking and I can't find a way to query by modification or creation date. What I really need is a query than in English would be, "all records modified today."

Is there a way to do that that I'm missing?

**Comment by gtalarico** [comment]
You need to either create intermediate derived columns using formulas eg. create a new column called "Date Modified" and use Airtable formulas to format it as "MM/DD/YY"

To do it directly with this library use the `formula=` parameter with the appropriate airtable formula 

https://airtable-python-wrapper.readthedocs.io/en/master/params.html#airtable.params.AirtableParams.FormulaParam
https://support.airtable.com/hc/en-us/articles/203255215-Formula-field-reference#date_and_time_functions

**Comment by gtalarico** [comment]
New formula module should help.
Here is a sample:
https://github.com/gtalarico/pyairtable/commit/b52be6cc99fd4e52541dc2bb1eedb6379732e4ea#diff-28df823d6114a99a655e50c9f3b704c265c32499c1b198e92b8b3924b1551108R67
