### ISSUE TITLE
Ideas for Next Major Version

### ISSUE THREAD

**Issue by gtalarico** [gtalarico/pyairtable#123]
Been thinking about starting a new version to improve some of the APIs and add new major features.

# 0. Rename lib

It's been suggested renaming lib, to `python-airtable` or similar.
Could be `pyairtable`

See #125 

### 1. Table vs Base

Implement two callses, `Table` and `Base`.
`Base` maps to a "Base" and all methods take a table name.
Or `Table` which takes name on init and holds. 
`Table` would be a light wrapper around the "Base" class.

```python
table = Base(api_key="key")
table.get("table_name", "recordId")
table.insert("table_name", *args)

# Table
table = Table("table_name", api_key="key")
table.get("recordId")
table.insert(*args)
```

In progress docs:
https://airtable-python-wrapper.readthedocs.io/en/version-2/api.html#api

### 2. Rename Apis

Rename + Remove some methods to simplify API and
align more closely with airtabe api

| old  | new | Airtable |
| ------------- | ------------- |------------- |
| `get()`  | keep? `get()`  | Retrieve: `GET base/recordId`
| `get_iter()`  | `iterate()`  | List: `GET base/`
| `get_all()`  | open ? `list()` `all()`  | List: `GET base/`
| `match()`  | use new `first(formula=)`  | List: `GET base/?filterByFormula`
| `search()`  | use `get_all(formula=)`  | List: `GET base/?filterByFormula` 
| `insert()`  | `create()`  | Create:`POST base/`
| `update()`  | keep  | Update: `PUT base/`
| `replace()`  | use `update(replace=True)`  | Update:`PATCH base/`
| `delete()`  | keep `delete()`  | Delete:`DELETE base/`=

In Progress docs:
https://airtable-python-wrapper.readthedocs.io/en/version-2/migrations.html

```

### 3. Querysets
Make tables  support queryset-like methods - think django Q() :)

Other Examples:
* https://docs.djangoproject.com/en/3.2/ref/models/querysets/#operators-that-return-new-querysets
* https://pypika.readthedocs.io/en/latest/2_tutorial.html

```python
all_records = table.records.all()
first = table.records.first()
some = table.records.filter()
one = table.get("recordId")
```

I am not fully convinced this is a good idea. 
Maybe this is implemented only in the higher level `orm.Model` class. 
I like that the client returns pure record response, in contrast to libraries like `pygithub` that wrap al response objects

### 4. Search / Filtering 
Remove search/match methods in favor of formula based query building. See renaming api above)

```python
table.list(formula=match({"Name", "X"}) # returns all that match
table.first(filter=some_formula) # returns first that match
```

### 5. Formulas

Would be cool to have some tooling to assist with building formulas, 
although not sure there is an elegant way to support all formulas.
https://support.airtable.com/hc/en-us/articles/203255215-Formula-field-reference

Could maintain binding for all funcs - might be a burden to maintain:

```python
from airtable.functions import Field, All, Or, Find

formula = And(Field("name") == "x", Field("age") == 20) # name is 'x' and age is 20
fromula = Find(Field("name"), "J") # name includes letter J
```

In progress iteration:
https://airtable-python-wrapper.readthedocs.io/en/version-2/api.html#formulas

### 6. Meta Api
Add support for https://airtable.com/api/meta to fetch schemas, etc
https://community.airtable.com/t/accessing-the-metadata-api/37080

```
from api.contrib import MetaApi

table = Table('base_id', 'table_name', 'apikey', meta_api=True)
table.schema()

```

### 7. Airtable Models (Orm Style Classes)
I have build model classes around tables in a few projects - could be cool to have a paved road for this.

```python
from airtabe.orm import Model

class Person(Model):
    name: str
    age: int
    
    class Meta:
        base_id = ''
        table_name = ''
        api_keu = ''

    >>> person = Person(name="x", age=21)
    >>> person.save() # calls `airtable.create()`
    >>> person.id
    'rec123asda'
    person.name = "y"
    person.save() # calls airtable.update('rec123asd')

    >>> person.delete()

    # Could be typed
    person.name == True
    # raise TypeError
```

Could also integrate with meta api

```
    >>> person.validate() #returns bool indicating if defined "fields" (name and type) match table schema
    True
```

In progress docs:
https://airtable-python-wrapper.readthedocs.io/en/version-2/orm.html

### 8. Better Date management
See #119 
Can we cast to from iso stamps?

### 9 . Better Attachment management
See #74 
Can we help users construct attachment record ?

>>> from api import attachment_record
>>> attachment_record(url="https://www.url.com/file/5YTJXioCQG0tYWPw6OPw", filename="xxx.jpg", ...)
```
   {
        "id": "att6f75cc83f1b648",
        "size": 26317,
        "url": "https://www.filepicker.io/file/5YTJXioCQG0tYWPw6OPw",
        "type": "image/jpeg",
        "filename": "33823_3_xl.jpg",
        "thumbnails": {
            "small": {
                 "url": "https://www.filepicker.io/api/file/Dy5gioxaShSUvHX0LgIC",
                 "width": 54,
                 "height": 36
             },
            "large": {
                 "url": "https://www.filepicker.io/api/file/ueYi00yRiqhuUn420UZA",
                 "width": 197,
                 "height": 131
             }
         }
    }
```

### 10. Developer Experience

1. Auto generate CHANGELOG?
Some libraries auto-generate change log - https://pygithub.readthedocs.io/en/latest/changes.html

2. Release Lib in CI?
Currently release process requires me to pull lastest and release from terminal using `make release`
Would be awesome to be able to release from ci when a tag is added:
https://github.com/PyGithub/PyGithub/blob/master/.github/workflows/pypi-release.yml

#### 11. Supported Formula:

- [ ] `"FIND('SomeSubText', {COLUMN_STR})=1")`

**Comment by gtalarico** [comment]
Latest development is here
Docs: https://pyairtable.readthedocs.io/en/latest/
Code: https://github.com/gtalarico/pyairtable/tree/main/

Tracker:
-[x] 1. Table vs Base
-[x] 2. Rename Apis
-[ ] 3. Querysets (might not) do this.
-[ ] 4. Search / Filtering (is `formula=match({})` enough?)
-[x] 5. Formulas
-[x] 6. Meta Api
-[x] 7. Airtable Models (Orm Style Classes)
-[x] 8. Better Date management
-[ ] 9 . Better Attachment management
-[x] 10. Developer Experience
-[ ] 11. Supported Formula (FIND)

**Comment by gtalarico** [comment]
@k-dal @hh-h would love to hear your input on new API, docs, new features, etc
Should be close to ready to release it, and Airtable has agreed to listed in the Docs 🎉 
https://pyairtable.readthedocs.io/en/latest/

**Comment by hh-h** [comment]
Hello! I don't really use airtable, we need it only for exporting data to CSV from tables. But I can suggest you one thing based on my programming experience.

I think something similar should be able for user convinience. 
```python

class Table:
    ...


class Base:
    ...

    def get_table(table_id: str) -> Table:
        ...


class Api:
    ...

    def get_base(base_id: str) -> Base:
        ...

    def get_table(base_id: str, table_id: str) -> Table:
        ...

```

**Comment by gtalarico** [comment]
That's a good idea, thank @hh-h

**Comment by gtalarico** [comment]
@hh-h is this what you were thinking?
https://github.com/gtalarico/pyairtable/pull/127/commits/1ddf65534961f7483e0fe8a805ad90a60d039507
