### ISSUE TITLE
Should this package be renamed

### ISSUE THREAD

**Issue by gtalarico** [gtalarico/pyairtable#125]
I don't love the name, it's long and causes some confusion - but may not be worth the work renaming.
Maybe for [version 2](https://airtable-python-wrapper.readthedocs.io/en/version-2/)...?

Some alternatives are: 
* `airtable` (used) 
* `python-airtable` (used)
* `airtable-python` (used)
* `airtable-python` (available)
* `pyairtable` (available)
* `airtable-python-wrapper` (keep as is :))

**Comment by hh-h** [comment]
pyairtable looks good

**Comment by k-dal** [comment]
A name change is a good idea. This is easily the best Python wrapper for Airtable's API, and I remember it took me a while to try it because I assumed the simpler names would be more stable. Now I know better, but I bet a simpler name would make it easier for others to find in the future.

Anyway, I second @hh-h's choice -- I like pyairtable (and I see @gtalarico already grabbed it on pypi!). 

Pyairtable would also be a great module name... 'from pyairtable import Airtable' would reduce confusion caused when other Airtable packages are installed in the same env.

**Comment by gtalarico** [comment]
Thank you both for your feedback. +1 on your rationale for changing @k-dal 

I was a bit afraid of changing because the package is already reference in a lot of projects, but I am starting to think it could be worth it.Here is what I was thinking

Repo: rename `airtable-python-wrapper` -> `pyairtable` (github maintains redirects for existing web links)
Pypi: Keep `airtabe-python-wrapper` for 0.x, create new `pyairtable` [on pypi](https://pypi.org/project/pyairtable/) for 1.x+
Docs: RTD can handle both version simultaneouly so old docs would still be accessible.
Ie. 0.x releases remain `airtable-python-wrapper` and `1.x+` become pyairtable. 
Is that confusing?

Alternatively, I could create new repo and just launch 1.0x as `pyairtable` as a new project and link in this repo as the new "successor"

**Comment by hh-h** [comment]
This (or similar) https://github.com/simonw/pypi-rename can be useful.

**Comment by jonathanlaniado** [comment]
How abour `airtable-py` or `airtablepy`? I also like `pyairtable`, but either way I think it makes sense to rename the package only in the newer `1.*` version.

**Comment by k-dal** [comment]
> Repo: rename `airtable-python-wrapper` -> `pyairtable` (github maintains redirects for existing web links)
This is smart. It guarantees any links to the repo still work while simultaneously introducing people to the new name. This plus a one-line "airtable-python-wrapper" is now "pyairtable" in the readme would make it all super clear.

> Pypi: Keep `airtabe-python-wrapper` for 0.x, create new `pyairtable` [on pypi](https://pypi.org/project/pyairtable/) for 1.x+
Agreed, this is another good call and makes it easy to put up a "final" 0.x release for any cases where requirements.txt has airtable-python-wrapper without a version. 

> Docs: RTD can handle both version simultaneouly so old docs would still be accessible.
👍

> Ie. 0.x releases remain `airtable-python-wrapper` and `1.x+` become pyairtable.
I agree with @jonathanlaniado; this makes the most sense.

> Is that confusing?
Nope!

**Comment by gtalarico** [comment]
Thank you all so much for your feedback. 
If any of you it's interested in contributing on 1.x let me know.
The work I have so far is on `version-2` branch, docs here:
https://airtable-python-wrapper.readthedocs.io/en/version-2/index.html

**Comment by k-dal** [comment]
@gtalarico I'm up for contributing. Let me know how I can help.

(One caveat - I'm a bit short on time these next few weeks (getting married and then traveling), but I'll have spare cycles afterward when things settle.)

**Comment by gtalarico** [comment]
`pyAirtable` reserved :)

![image](https://user-images.githubusercontent.com/9513968/127370281-49f2b2e2-15dd-4945-9295-b97f2afb65c1.png)

**Comment by gtalarico** [comment]
### Summarizing Considerations

Advantages of not renaming:
* Renaming might cause some confusion for older library users

Advantages of renaming:
* Old `airtable` module name caused import errors because it would clash with user's file named `airtable.py`.  
(#108 #98 #95 #24) - `pyairtable` is less likely to clash. 
* Renaming also reduces changes of clashing with other packages that use module name `airtable` (#124 )
* New name can also be library and package name- eg `pip install pyairtable` > `import pyairtable` (compare it to `pip install airtable-python-wrapper` - `import airtable`.
* New name makes it easier for users to distinguish new Api design which introduces a few breaking changes from 0.x interface - ie old users won't accidentally upgrade and break their old code.


### Conclusion
Moving forward with renaming effort!
The new api is well on it's way and can be seen here - feedback on new features + docs is very much welcome!
https://airtable-python-wrapper.readthedocs.io/en/version-2/getting-started.html

Lastly, wanted to share that I reached out to the Airtable and they accepted my suggestion of including the library in the official Airtable Api Docs!

>  _heard back from our engineers and after reviewing your Python client, they have decided to add it to our API documentation. Thanks again for all the work you've done to build and maintain this, and for reaching out to us about it! I'm not sure exactly when the documentation will be updated, but my guess would be sometime in the next few weeks._

I have asked them to hold off on including until `pyairtable` is release. This will be a nice motivator to get everything ironed out for a big new release : )


### Packaging
* Github will be renamed `airtable-python-wrapper` -> `pytairtable`
* `pyairtable` will be a new package. Old package will be maintained as is for users that want to continue using the old library but will not receive any further updates.

**Comment by gtalarico** [comment]
Done
