### ISSUE TITLE
Add support for type checking

### ISSUE THREAD

**Issue by fmorato** [gtalarico/pyairtable#135]
Currently, using mypy gives an error that the library doesn't have type hints.

    error: Skipping analyzing "pyairtable": found module but no type hints or library stubs

It would be nice to have support for it, as the type annotations are already done.

**Comment by gtalarico** [comment]
Thanks.
Do you know what needs to be done to play nice with mypy? I have set this up before but don't recall.

**Comment by fmorato** [comment]
According to [PEP 561](https://www.python.org/dev/peps/pep-0561/), adding an empty `py.typed` file to the built package is enough.
