### ISSUE TITLE
Create new select option through script

### ISSUE THREAD

**Issue by saaalik** [gtalarico/pyairtable#137]
![image](https://user-images.githubusercontent.com/65087495/135047693-9c7fa5a0-4251-4405-9a3e-0615762ec7f6.png)
I can not create new record with 
```python
table.create({'user': '34443344',"links":['8kr99F7rCP', '64AAwA8f5B', 'vE4TzESFee']})
```

`'8kr99F7rCP'` and `'64AAwA8f5B'` are already defined in the multiple selection field, but when I try adding a new item, it gives me
```
[Error: {\'type\': \'INVALID_MULTIPLE_CHOICE_OPTIONS\', \'message\': \'Insufficient permissions to create new select option ""vE4TzESFee""\'}]')
```

Is there a way to give permissions to add new select options through the module?

**Comment by gtalarico** [comment]
Permissions can be only managed by the Enterprise Api
https://airtable.com/api/enterprise

Closing this since we won't be able to fix, 
but feel free to reply and continue the conversation

**Comment by tagawa** [comment]
Airtable may have changed their rules as I was able to do this by setting typecast (the second parameter) to True, e.g.:

`table.create(fields, True)`
or
`table.batch_create(records, True)`
