### ISSUE TITLE
How to get formulas with OR

### ISSUE THREAD

**Issue by tr-gis** [gtalarico/pyairtable#138]
Hi. I can see from the documentation that using match function we can build formulas. 

`match({'Name':'Rey,'Age':28})` returns `"AND({Name}='Rey',{Age}=28)"`

I would like to get formula like `OR({Status}="Out of Stock",  {Status}="Phased Out")`. I could not find any reference to getting this done.

**Comment by gtalarico** [comment]
You can take a look at the code for match and make a copy of it using OR:

https://pyairtable.readthedocs.io/en/latest/_modules/pyairtable/formulas.html#match

You can also construct the formula from scratch using EQUAL and OR as shown in the source code above. This is most flexible as it lets you compose any logical combination eg. `(1 and 2) or 3`

Looking forward, if we think this is a common use case We could add a new function (e.g. match_or) or a parameter (`match={...}, all=False`).

**Comment by tr-gis** [comment]
got it. thanks :)
