### ISSUE TITLE
Issue with table.update()

### ISSUE THREAD

**Issue by Panda-52** [gtalarico/pyairtable#146]
Can someone help to address the issue around updating a table field value using table.update():

**Code Attempt 1:**
` Table.update('recELQAmelax4291X', {"Hours Used": 40}) `
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-60-e03cbf91d065> in <module>
      1 ## Update a record in the Projects Table ##
      2 
----> 3 Table.update('recELQAmelax4291X', {"Hours Used": 40})
      4 
      5 # Table.update([{record_id = "recELQAmelax4291X", fields={"Hours Used": 21}}])

TypeError: update() missing 1 required positional argument: 'fields'
---------------------------------------------------------------------------

**Code Attempt 2:**
` Table.update({id:'recELQAmelax4291X', fields:{"Hours Used": 40}}) `

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-62-126834bbd9c9> in <module>
      3 # Table.update('recELQAmelax4291X', {"Hours Used": 40})
      4 
----> 5 Table.update({id:'recELQAmelax4291X', fields:{"Hours Used": 40}})

NameError: name 'fields' is not defined

**Comment by wanghaisheng** [comment]
@gtalarico for update we need id first
how to exact get id from filed value  lets say a id or name filed
