### ISSUE TITLE
Support Match for Any or All

### ISSUE THREAD

**Issue by gtalarico** [gtalarico/pyairtable#150]
[ Placeholder] 
https://github.com/gtalarico/pyairtable/pull/148#issuecomment-1093159389

**Comment by a5r0n** [comment]
I think it's better to add 2 new methods, `match_all` & `macth_any`
It is more clear what the function does. then adding `all=True` param to already exists `match` function

**Comment by gtalarico** [comment]
fixed via https://github.com/gtalarico/pyairtable/pull/174
