### ISSUE TITLE
How are you supposed to represent date/datetime in `Table.create`

### ISSUE THREAD

**Issue by Juliusfrank11** [gtalarico/pyairtable#152]
Passing values as the native python `datetime` results in the error
```
TypeError: Object of type datetime is not JSON serializable
```

To overcome this, one can use `datetime.isoformat()` which converts the `datetime` object to an ISO formatted string, but then one gets an `INVALID_VALUE_FOR_COLUMN` error from the Airtable API. 

I am on Python 3.10.2 and pyairtable version 1.0.0.post1.

Replicatable code:
```python
import datetime
# make `table` an Airtable table with a Date field named "Date"
dt = datetime.datetime(2022,4,18,12,6,2)
table.create({'Date':dt})
table.create({'Date':dt.isoformat()})
```

**Comment by gtalarico** [comment]
Can you try the provided string formatter from the utils module?

https://pyairtable.readthedocs.io/en/latest/utils.html#pyairtable.utils.datetime_to_iso_str

**Comment by Juliusfrank11** [comment]
> Can you try the provided string formatter from the utils module?
> 
> https://pyairtable.readthedocs.io/en/latest/utils.html#pyairtable.utils.datetime_to_iso_str

just tried it and got the same `INVALID_VALUE_FOR_COLUMN` error

**Comment by gtalarico** [comment]
Can't reproduce this. 
Can you check your column names and types?

```
import os
from datetime import datetime
from datetime import date
from pyairtable import Table
from pyairtable.utils import datetime_to_iso_str, date_to_iso_str

apikey = os.environ["AIRTABLE_KEY"]
base_id = "<baseid>"
table_name = "TEST_TABLE"
table = Table(apikey, base_id, table_name)

date = datetime.now()
datetime = datetime.now()
table.create({
    "date": date_to_iso_str(date),
    "datetime": datetime_to_iso_str(datetime)
    })
```

![image](https://user-images.githubusercontent.com/9513968/164064620-782c0695-5ec4-49a1-acdc-fb77647a3d81.png)

**Comment by Juliusfrank11** [comment]
Hello,

For some reason, `date_to_iso_str` worked on my column. Not sure why, as the underlying data was obtained from SQL as `DATETIME` and was in `pd.Timestamp` format.

The time part wasn't needed for my application so this is good enough for me but thought I should let you know.

**Comment by gtalarico** [comment]
Thanks for the update
