### ISSUE TITLE
Receiving UTF8 encoded json

### ISSUE THREAD

**Issue by NicoHood** [gtalarico/pyairtable#164]
Currently special characters like `ö` are encoded like this: `\u00f6`. This does not happen with curl, so I guess it is an issue with the library here.

My wild guess is that we need to add `accept-charset="UTF-8"` as header to the request. I [inspected the curl command](https://stackoverflow.com/a/26644485) and it requests `Content-Type: application/json; charset=utf-8`.

**Comment by gtalarico** [comment]
can you provide a reproducible test case?
I am not seeing the same issue here.

<img width="666" alt="image" src="https://user-images.githubusercontent.com/9513968/178175533-1bcc562d-628d-4e45-9b51-f655c62a3ea1.png">

<img width="385" alt="image" src="https://user-images.githubusercontent.com/9513968/178175561-7d2af7d0-c91d-4608-8938-6bd8b32dbe5b.png">

**Comment by NicoHood** [comment]
I noticed that I came from this way of printing:
```py
print(json.dumps(data, indent=4, sort_keys=True))
```

Without the `json.dumps()` it is printed correct. But I think this is a general mistake by me, not the library, right?
https://stackoverflow.com/questions/18337407/saving-utf-8-texts-with-json-dumps-as-utf8-not-as-u-escape-sequence

Sorry, I never ran into this before.
