### ISSUE TITLE
"match" only support AND operator, I need OR.

### ISSUE THREAD

**Issue by instasck** [gtalarico/pyairtable#170]
I have a "Status" field.
formula = match({"Status": "ACTIVE", "Status": "PENDING START"})
This will have an AND, while I need OR.

Solution
I used this instead of match.
formula_string = "OR({statustest}='ACTIVE',{statustest}='PENDING START')"

Better have it coded. match should have OR / AND options.

**Comment by gtalarico** [comment]
Dup of #150
Until this is implemented you can look at code for match(). It just builds a formula using AND so it's easy to create your own helper function for matching with OR
