### ISSUE TITLE
Make API_BASE_URL configurable

### ISSUE THREAD

**Issue by jvhellemond** [gtalarico/pyairtable#172]
If `API_BASE_URL` were configurable, then pyAirtable could be used to send write requests (POST, PATCH, PUT, DELETE) via the Sequin proxy:

> See https://docs.sequin.io/airtable/reference#how-to-write-through-the-proxy

Sequin proxies requests to the Airtable API. All it requires is to send API requests to `https://proxy.sequin.io/api.airtable.com` instead of `https://api.airtable.com`.

**Comment by gtalarico** [comment]
I have not tested this, not it's documented, but you should be able to do this:
```
from pyairtable import Table
Table.API_BASE_URL = "https://proxy.sequin.io/api.airtable.com"
```

Let me know if it works

**Comment by NicoHood** [comment]
Would be worth to document :)
