### ISSUE TITLE
ORM: Model.save() method fails due to attempting to write to computed fields 

### ISSUE THREAD

**Issue by larsakerson** [gtalarico/pyairtable#177]
The `Model.save()` method is failing for me when the Airtable API rejects the payload, because it includes computed fields. These computed fields are not updated locally in my code, but they are included in the model and get pushed to Airtable in the record update by default.

Is there a way to set a flag on Field classes to indicate that particular fields should not be saved directly, but instead are computed in Airtable?

**Comment by gtalarico** [comment]
This does not exist but would be probably be a good addition
