### ISSUE TITLE
ORM is missing a view_id option

### ISSUE THREAD

**Issue by NicoHood** [gtalarico/pyairtable#185]
To specify the view to work on. Should be quite easy to add, right?

**Comment by mesozoic** [comment]
I'm not sure it makes sense to have an ORM limited to results from a view. Conceivably that could result in a situation where a record can't be retrieved once it's created, if it doesn't match the conditions on the view, and the library has no real way of knowing whether that's going to happen. (Not even if we're very clever; we can't inspect a view's filters through the API.)

You can still do something like `Model.all(view="My View")`. Does that address your use case?

**Comment by NicoHood** [comment]
Yeah, you are right.
