### ISSUE TITLE
ORM specify table_id instead of table_name

### ISSUE THREAD

**Issue by NicoHood** [gtalarico/pyairtable#186]
Specifying the name looks weird and wrong to me. I want to use ids whenever possible. We should also add a table_id instead of just a table_name

**Comment by NicoHood** [comment]
Even in the docs it is named as table_id:
https://github.com/gtalarico/pyairtable/blob/main/pyairtable/orm/model.py#L79

**Comment by mesozoic** [comment]
Have you tried passing a table's ID as the `table_name` parameter? It should work for both "standard" and ORM use cases. If so, let's close this issue; if not, please post steps to reproduce any problems you encounter.

**Comment by mesozoic** [comment]
Have you tried passing a table's ID as the `table_name` parameter? It should work for both "standard" and ORM use cases. If so, let's close this issue; if not, please post steps to reproduce any problems you encounter.
