### ISSUE TITLE
ORM specify fields as id, not as name

### ISSUE THREAD

**Issue by NicoHood** [gtalarico/pyairtable#187]
It should be possible to make use of the `return_fields_by_field_id` option with ORM as well

**Comment by NicoHood** [comment]
Even in the docs it is named as table_id:
https://github.com/gtalarico/pyairtable/blob/main/pyairtable/orm/model.py#L79

**Comment by aleafa** [comment]
Sounds like you may be describing two different things. You *can* use the Airtable table ID (e.g., `tbl1234567890`) as the `table_name` in the ORM config. I don't *think* you can currently use field IDs (e.g., `fld1234567890`) in an analogous way, though that would be nice!

**Comment by NicoHood** [comment]
My comment (deleted now) was referring to this issue: https://github.com/gtalarico/pyairtable/issues/186
I posted it on the wrong issue, sorry

**Comment by mesozoic** [comment]
I think this behavior would be either implicit (the library guesses you're using field names if they start with `fld` and are the correct length) or explicit (you have to pass a flag, either to the Field or to Model.Meta). I usually [prefer being explicit](https://peps.python.org/pep-0020/).

Patches that follow our [contribution guidelines](https://github.com/gtalarico/pyairtable#contributing) are very welcome! :)
