### ISSUE TITLE
ORM specify configuration and API key outside the code

### ISSUE THREAD

**Issue by NicoHood** [gtalarico/pyairtable#192]
Hi,
I have a simple ORM Model and of course I dont want to place any API keys inside the code, and I want to make those settings configurable anyways (as I have special testing and live databases on airtable).

```py
class AirtableEvent(airtable.Model):
    title = airtable.fields.TextField("Titel")
    description = airtable.fields.TextField("Beschreibung")
    start = airtable.fields.DatetimeField("Start")
    end = airtable.fields.DatetimeField("Ende")
    url = airtable.fields.TextField("Url")
    address = airtable.fields.TextField("Adresse")
    location = airtable.fields.TextField("Ort")
    status = airtable.fields.TextField("Status")
    recurring = airtable.fields.CheckboxField("Wiederkehrend")
    source = airtable.fields.TextField("Quelle")
    google_calendar_meta = airtable.fields.TextField("Google Calendar Meta")
    google_uid_meta = airtable.fields.TextField("Google Uid Meta")
    google_sequence_meta = airtable.fields.IntegerField("Google Sequence Meta")
    trash = airtable.fields.CheckboxField("Papierkorb")

    class Meta:
        # This must be loaded from the configuration
        base_id = None
        table_name = None
        api_key = None

    @classmethod
    def load_json_config(cls, api_key, config):
        cls.Meta.base_id=config["base_id"]
        cls.Meta.table_name=config["table_id"]
        cls.Meta.api_key=api_key
```

Now if you use the class as it is right now, it will fail with `ValueError: Meta.base_id must be defined in model`

I can surpress this by setting it to a non-empty string and set those metadata afterwards. But how can we do this in a more proper way? I am searching for a good solution, do you have any idea?

**Comment by aleafa** [comment]
My workaround has been to create a base class built on `Model` that loads the `base_id` and `api_key` from environment variables and is then inherited by all my data models. It's kind of wonky to have to set a placeholder string for the `table_name` like you say, but it works.

It would be nice to have a smoother way to set config variables.

**Comment by gtalarico** [comment]
@NicoHood I think your solution seems ok.

If we think is is an important problem we could do something like this:
```
    class Meta:
        ...
        disable_validation = True  # disable checking of values
```

Then in `Model` we check for this before calling `_validate_class()`

**Comment by NicoHood** [comment]
Another idea would be to pass the meta data at model creation. I mean, why not? But this would require us to also pass it for the all() function etc.

I dont think that defining the ids like this is a good idea anyways, I would remove or at least deprecate it. In the end nobody wants to hardcode stuff, so this is no long-term solution I think.

**Comment by gtalarico** [comment]
The reason fields are nested inside Meta is because I don't want to pollute the model namespace with "meta" /non-model attributes.

I think every field in the model should be properties of the "model/table", and everything else goes in meta. 
I see this as a common pattern in many ORMs I have used it and I like it ([django](https://docs.djangoproject.com/en/4.1/ref/models/options/#order-with-respect-to), flask-marshmellow, [factory boy](https://factoryboy.readthedocs.io/en/stable/orms.html#factory.django.DjangoOptions.django_get_or_create), etc)

Your use case is interesting and should be supported but not at cost of making simpler usage more complicated.

I think there are better ways to solve this. 
One that comes to mind is to just override "Meta" with a custom class that can load values dynamically.
It would have to think more about this but my bandwidth for this project is currently pretty low

**Comment by NicoHood** [comment]
Yeah, we can use the config I made and move everything there as well. Was thinking about that too, but unsure first.

Maybe more in this direction:
```py
@dataclass
class ContactConfig:
    first_name_field_id: str
    last_name_field_id: str

    # https://florimond.dev/en/posts/2018/10/reconciling-dataclasses-and-properties-in-python/
    base_id: str
    _base_id: str = field(init=False, repr=False)
    table_id: str
    _table_id: str = field(init=False, repr=False)
    api_key: str
    _api_key: str = field(init=False, repr=False)

    @property
    def api_key(self) -> str:
        return __self._api_key

    @api_key.setter
    def api_key(self, api_key: str):
        self._api_key = api_key

    @property
    def table_id(self) -> str:
        return __self._table_id

    @table_id.setter
    def table_id(self, table_id: str):
        self._table_id = table_id

    @property
    def base_id(self) -> str:
        return __self._base_id

    @base_id.setter
    def base_id(self, base_id: str):
        self._base_id = base_id

    @classmethod
    def from_json_config(cls, config):
        return cls(
            base_id=config["base_id"],
            table_id=config["table_id"]
            # Other cases left out to just demonstrate the idea
        )
    
    def get_field_id(self, field: fields.Field) -> str:
        # TODO I am not sure if you can reference fields of another class like that
        match responseNumber:
            case Contact.first_name:
                return __self.config.first_name_field_id
            case Contact.last_name:
                return __self.config.last_name_field_id
            # Other cases left out to just demonstrate the idea
            case _:
                raise ValueError("Unknown field id")

class Contact(Model):
    first_name = fields.TextField()
    last_name = fields.TextField()
    email = fields.EmailField()
    is_registered = fields.CheckboxField()
    partner = fields.LinkField(Contact, lazy=False)

    __config: ContactConfig

    def __init__(self, config, *args, **kwargs):
        self.__config = config
        super(Contact, self).__init__(*args, **kwargs)
```

**Comment by NicoHood** [comment]
So coming back here a few days later I still have no idea how we should dynamically pass the api key. I find it very hard to google for good resources. There are some existing ORM solutions, but they all fit just for SQL, but we need to build our own. And those are massivly complex (at least at my current know-how level) to understand.

@gtalarico You have more experience in that. If it is only the api key which we need to pass in, what would be the best way to do that? I think if I understand that mechanism I can extend it for the base id etc.

**Comment by mesozoic** [comment]
Weighing in a bit late, but I think one option is for `Meta` attributes to be typed `Union[str, Callable[[], str]]` and to either use the value as-is _or_ call the callable the first time (or every time?) we need to get the value. That way implementers can do whatever they need to do, pull from `os.environ`, etc.

+1 to keeping this in `Meta` and not polluting the namespace of the actual Model subclass.
