### ISSUE TITLE
Create and update commands do not take return_fields_by_field_id into account

### ISSUE THREAD

**Issue by NicoHood** [gtalarico/pyairtable#194]
The record returned will always have names, not IDs. We need to fix it. I guess it is quite simple.

**Comment by NicoHood** [comment]
requires pyairtable 1.4.0

**Comment by mesozoic** [comment]
I have a hunch that this is because `returnFieldsByFieldId` needs to be passed in the POST body rather than as query params in the URLs. I'm working on this part of the code already in #247 so I'll cut another branch for this issue soon.
