### ISSUE TITLE
Git hooks and stuff are not working with python 3.10 and behave weird

### ISSUE THREAD

**Issue by NicoHood** [gtalarico/pyairtable#195]
I find it very challanging to commit something to this repository. Here is why:
* python 3.10 does not work, it requires a new shpinx version and a change in the config.py file (set `lang` to `en`)
* When I try to push it seems to run the test on the current file system files, not from the git. If you have unstaged changes, you need to stash them first. The script does not automate this
* If you then stash the changes and push the changes, the script will unstash the changes for you. That is ultra weird and leads to undefined behavior it seems. I have no idea what is happening

**Comment by NicoHood** [comment]
It seems that the requirements-dev.txt file is not autogenerated. I have no idea which packages are safe to upgrade, but we need to upgrade sphinx for python 3.10:
https://github.com/sphinx-doc/sphinx/issues/9562

**Comment by gtalarico** [comment]
* you can use pyenv and use python 3.7/8/9 
* updating sphinx is ok. just install latest using pip and update requirerements-dev.txt to version

> When I try to push it seems to run the test on the current file system files, not from the git. 
Not sure what you mean. tests will always run against whatever is in your file system. 

> If you then stash the changes and push the changes, the script will unstash the changes for you.
I don't think that's correct. You can see the scripts source code. all it does is run test + lint

If you dislike githooks you can always disable them . They are just a convenience.

**Comment by NicoHood** [comment]
But I dont have an older version of python installed on my system. Archlinux just has the latest version. Or is there some magic I dont know yet?

Would you mind bumping shpinx in your upstream repo? I really dont know the side effects and if it all works fine, as I have not set it up or used it by now.

**Comment by gtalarico** [comment]
It's generally not advisable to use your system's python for development. Venv helps but IMHO it's even better is to use pyenv to install and manage your own installation.

When you are developing libraries you have to be able to switch and run code and test in various runtimes. pyenv + tox allows project to run test against all versions.

As far as sphinx support happy to bump up it up and update conf.py as long as it doesn't break development in 3.8/3.9

**Comment by mesozoic** [comment]
Hi, I think this should be resolved with some of the recent changes we've made, so I'm going to close this issue. 

If you pull main and run `git config --local --unset core.hooksPath && make setup`, it will remove the old githooks and replace them with [pre-commit](https://pre-commit.com) running inside a tox-managed environment. Docs and tests now use tox as well, so you don't need to mess with your system python.

+1 to using [pyenv](https://github.com/pyenv/pyenv) to manage multiple Python installations. You can set it up with something like this in your local Git repo:
```
% pyenv install 3.{7..11}
% echo 3.{7..11} | xargs -n1 pyenv latest | xargs pyenv local
```
