### ISSUE TITLE
batch_insert in documentation?

### ISSUE THREAD

**Issue by NicoHood** [gtalarico/pyairtable#197]
This is a typo, right?
https://pyairtable.readthedocs.io/en/latest/api.html#pyairtable.api.Api.batch_create

![grafik](https://user-images.githubusercontent.com/6888294/197158292-3b7dc4a1-832e-41aa-baf2-cb47b799d4da.png)

**Comment by gtalarico** [comment]
Yep!

![image](https://user-images.githubusercontent.com/9513968/197591659-bdc2591a-02a2-4fa7-b095-ce45371608ba.png)
