### ISSUE TITLE
documentation says retrying is in 1.3.0, but it's not

### ISSUE THREAD

**Issue by noamraph** [gtalarico/pyairtable#201]
Hi,

The documentation (https://pyairtable.readthedocs.io/en/latest/api.html#retrying) says that `Retrying` is new in 1.3.0. However, it's not yt available in 1.3.0 (according to the 1.3.0 tag).

Thanks,
Noam

**Comment by gtalarico** [comment]
Yep that's looks like a mistake, thanks for reporting.

**Comment by gtalarico** [comment]
Should be fixed
<img width="643" alt="image" src="https://user-images.githubusercontent.com/9513968/215442557-877b5bae-b25c-4e29-b6e9-eb4ca96f23cc.png">
