### ISSUE TITLE
No support for iterating over bases and tables?

### ISSUE THREAD

**Issue by mjmare** [gtalarico/pyairtable#204]
I may be wrong but it seems that the Api, Base and Table all offer the same API to manipulate records. There is no support to iterate over Bases and over Tables? I would have expected the Api class to provide a way to get all Bases, the Base class to provide a way to get all Tables, and the Table class to provide a way to get all fields. 

PS thx for the package!

**Comment by mjmare** [comment]
Bit new to all this, so thx for the pointers. Turns out you need a special token for the metadata API, which I can't get ATM because there is a waitlist. Bummer. 


PS the first example on https://pyairtable.readthedocs.io/en/latest/metadata.html contains a small error: get_bases should be get_api_bases.

FYI, with this code 
```
from pyairtable import metadata

key = '<some regular API key>'
api = Api(key)
results = metadata.get_api_bases(api)
```
I got this error: 
```
('404 Client Error: Not Found for url: https://api.airtable.com/v0/meta/bases', "404 Client Error: Not Found for url: https://api.airtable.com/v0/meta/bases [Error: {'type': 'NOT_FOUND'}]")
```
Which might be related to me using a regular API key, but then I would have expected an authentication error.

**Comment by mjmare** [comment]
Thx for the prompt replies.

**Comment by marks** [comment]
@mjmare stumbled upon this and just FYI, anyone can now use the Metadata API to get a list of bases or retrieve a base's schema (both of which @gtalarico has implemented in pyairtable already 🙌 ) _when authenticating with a Personal Access  or OAuth token_. 

More info in the changelog [here](https://airtable.com/developers/web/api/changelog#anchor-2022-11-15)

**Comment by mesozoic** [comment]
This is supported today via `pyairtable.metadata` and anyone can use it now, so I'm going to resolve the issue.
