### ISSUE TITLE
Adding metadata API (2022-11-15 update)

### ISSUE THREAD

**Issue by joe-irving** [gtalarico/pyairtable#208]
Airtable has just released a major update to the API, detailed [in the new docs](https://airtable.com/developers/web/api/changelog).

This includes a change to personal access tokens for authentication, and a few new classes (with new methods) which I have tried to lay out below to plan adding them to this wrapper.

Completely new classes and their methods:

* Fields
    * Update Field
* Comments
    * Update comment
    * Delete comment
* Webhooks
     * List payloads
     * Disable/Enable notifications
     * Delete
     * Refresh

And new methods for existing classes (same format):

* Record
    * List Comments
    * Create Comment
* Table
    * List fields
    * List views
    * Create field
    * 'Upsert' option in the batch_update method
* Base
   * Get Schema (List tables)
   * List webhooks
* Api
   * List bases
   
Also added were a few methods for enterprise users only so probably not a priority. 

I don't know if this is the best way to go about tracking adding this functionality, so suggestions welcome.

**Comment by gtalarico** [comment]
This is great. Thanks for organizing this @joe-irving 
Will be tons of work 😮‍💨 😆

**Comment by BAPCon** [comment]
I'm about halfway through webhooks
