### ISSUE TITLE
Upserts on table

### ISSUE THREAD

**Issue by dhanaschenniappan** [gtalarico/pyairtable#216]
The Airtable API is supporting upset functionality now. This feature is very useful when we want to update the records based on a specific key instead of system object ID. Can we implement this feature in here also?

**Comment by marks** [comment]
Big +1 -- I started at https://github.com/gtalarico/pyairtable/pull/209 and was hoping for some feedback/guidance from @gtalarico when he has a chance

**Comment by gtalarico** [comment]
I'm on it, just need time to review and incorporate. Issues have been stacking up and I am a bit short on time.

btw @marks if your team can allocate any resources to this project I would be happy to add you or anyone else as a contributor to repo to help keep things moving a bit faster.

**Comment by BAPCon** [comment]
@gtalarico I'd like to take a crack at some issues, any order of operation you have in mind?
