### ISSUE TITLE
Create table and create base functions

### ISSUE THREAD

**Issue by gnoluna** [gtalarico/pyairtable#235]
As far as I know from the documentation, we can only operate on records of an existing table. Are you planning to wrap [create table](https://airtable.com/developers/web/api/create-table) and [create base](https://airtable.com/developers/web/api/create-base) from airtable api as well?

**Comment by BAPCon** [comment]
Adding in soon, just trying to figure out the right way to go about it

**Comment by mesozoic** [comment]
Apologies for the confusion, this is still on the roadmap but is not addressed by the PR linked above. I had the wrong PR#.

**Comment by SergioB-dev** [comment]
> this is still on the roadmap

Do you think someone is currently working on this? I can see this one through if not.

**Comment by SergioB-dev** [comment]
I am in need of this functionality for a project I'm working on. So I've forked this repo and extended it with the following functionality that I use locally:
- create table
- list all tables (useful for getting a base's schema - only way to see an existing [field's type](https://airtable.com/developers/web/api/model/field-type)

I plan to clean everything up and open a PR. I think others will find it useful.

**Comment by mesozoic** [comment]
There is an open PR for this linked above (#311) that is about ready to merge. You can [read the docs here](https://pyairtable--311.org.readthedocs.build/en/311/metadata.html). Feel free to leave feedback on that branch.

**Comment by mesozoic** [comment]
This was resolved in #311
