### ISSUE TITLE
Support for NocoDB

### ISSUE THREAD

**Issue by alx-xlx** [gtalarico/pyairtable#264]
I don't know where to put this but it would be great if a python api for nocodb is also put into place.
I really like pyairtable because of its simplicity. Is there any chance of this happening ?

**Comment by mesozoic** [comment]
NocoDB looks neat, but glancing at their [API](https://apis.nocodb.com/#tag/DB-Table-Row/operation/db-table-row-list) it looks different enough from Airtable's that I don't think this library is going to be compatible. It looks like there is already a [NocoDB client library](https://pypi.org/project/nocodb/) that I recommend you check out instead.
