### ISSUE TITLE
'Api' object has no attribute 'table'

### ISSUE THREAD

**Issue by rezashahabedin** [gtalarico/pyairtable#283]
when i try the sample code with proper a token, i recieve an error saying 
AttributeError: 'Api' object has no attribute 'table'

sample code:
import os
from pyairtable import Api
api = Api(os.environ['AIRTABLE_API_KEY'])
table = api.table('appExampleBaseId', 'tblExampleTableId')
table.all()

source:
https://pyairtable.readthedocs.io/en/latest/getting-started.html

**Comment by mesozoic** [comment]
Hi @rezashahabedin – you are looking at the `latest` docs branch, which points to the (soon to be released) 2.0 version of the library. If you're using 1.5, please take a look at `stable`: https://pyairtable.readthedocs.io/en/stable/getting-started.html
