### ISSUE TITLE
Loading a base with Base() and name overwrites id 

### ISSUE THREAD

**Issue by hkbombus** [gtalarico/pyairtable#290]
Ive been using Base with the name instead of id: 

"""
class Base(ApiAbstract):

    """
    Represents an Airtable Base. This calss is similar to :class:`~pyairtable.api.Api`,
    except ``base_id`` is provided on init instead of provided on each method call.

    Usage:
        >>> base = Base('apikey', 'base_id')
        >>> base.all()
    """
"""

If you provide Base('apikey', 'base_name') it still works. It creates the correct base object but it overwrites base_id with 'base_name' and drops the the name. This was not a problem until I tried to do other things further down the line and it was using the name instead of the id. 

![bug](https://github.com/gtalarico/pyairtable/assets/67481069/126dc275-1864-4856-ac98-fdb2dffcd5a9)

**Comment by mesozoic** [comment]
I'm not sure this has ever been explicitly supported behavior, but I'd still like to reproduce the problem you're seeing. Can you give an example of the sort of code that worked with 1.5 and doesn't work with 2.0?

**Comment by mesozoic** [comment]
Going to close this, as I don't believe the Airtable API has ever supported using base names instead of IDs.
