### ISSUE TITLE
`Api.all()` not present but indicated in `Api` docstring

### ISSUE THREAD

**Issue by krishnadesai-color** [gtalarico/pyairtable#297]
The docstring for `Api()` gives an example usage that doesn't actually work given the `all()` method does not exist.
https://github.com/gtalarico/pyairtable/blob/6d8f7b118cd8c36baad9733cbc90462c49267140/pyairtable/api/api.py#L25-L27

Is the docstring incorrect or was the method inadvertently deleted?

**Comment by mesozoic** [comment]
Good catch! Embarrassingly, I saw this immediately _after_ I pushed the 2.1.0 release, so I'm going to follow the advice in [What to do when you botch a release](https://snarky.ca/what-to-do-when-you-botch-a-release-on-pypi/) and release 2.1.0.post1 with the docs fixed.

**Comment by krishnadesai-color** [comment]
Thanks @mesozoic
