### ISSUE TITLE
Update does not accept return_fields_by_field_id parameter

### ISSUE THREAD

**Issue by NicoHood** [gtalarico/pyairtable#307]
Same issue as https://github.com/gtalarico/pyairtable/issues/194

This PR should have fixed it:
https://github.com/gtalarico/pyairtable/pull/252

But the parameter is still missing:
https://pyairtable.readthedocs.io/en/stable/_modules/pyairtable/api/table.html#Table.update

**Comment by mesozoic** [comment]
That's true! Unfortunately this is a limitation of the Airtable API; passing `returnFieldsByFieldId` to the update endpoint returns a 422 (unlike the batch update endpoint, which does the right thing). 

In the branch you mentioned, there's a [commented-out test](https://github.com/gtalarico/pyairtable/blob/2e4f3b896739c5d7e80f339c19a8b58d9d14f5d0/tests/integration/test_integration_api.py#L68) showing how we _could_ test it, if it were supported.

**Comment by NicoHood** [comment]
WTF? Alright, wouldnt it make sense to use the batch api then? I mean we could keep the same syntax and whenever airtable fixes this issue we could switch the call internally? That would make more sense, as we do not need to work around in the user code. Or is there any advantage in the "normal", single update call?

**Comment by marks** [comment]
Hi @NicoHood & @mesozoic - [the Airtable PATCH/PUT endpoints for a single record](https://airtable.com/developers/web/api/update-record) [now](https://airtable.com/developers/web/api/changelog#anchor-2023-10-03) support `returnFieldsByFieldId`

**Comment by NicoHood** [comment]
Nice! So then we could just enable it, right?

**Comment by mesozoic** [comment]
I'll reopen the issue. Pull requests are welcome!

**Comment by NicoHood** [comment]
I am sorry I aint got time to work on this. I know the fix is easy, but I have other priorities. Would be nice if someone else could add this parameter :-)

**Comment by marks** [comment]
@NicoHood - I believe PR #320 takes care of this for you if you want to go over and subscribe for updates over there

**Comment by mesozoic** [comment]
Thanks for resolving this issue, @marks!
