### ISSUE TITLE
Error using sample

### ISSUE THREAD

**Issue by gismcieri** [gtalarico/pyairtable#317]
Hi,

Installed pyairtable a few days ago and have tried on and off to connect to my environment using the code sample from the docs page

```
import os
from pyairtable import Api
api = Api(os.environ['AIRTABLE_API_KEY'])
table = api.table('appExampleBaseId', 'tblExampleTableId')
print (table.all())
```
and i always get the following error. I have tried various different things to get it to work and have been unsuccessful. 

Traceback (most recent call last):
  File "Pathtofile\pyairtableTesting.py", line 2, in <module>
    from pyairtable import Api
  File "C:\miniforge3\envs\main37\lib\site-packages\pyairtable\__init__.py", line 3, in <module>
    from .api import Api, Base, Table
  File "C:\miniforge3\envs\main37\lib\site-packages\pyairtable\api\__init__.py", line 1, in <module>
    from .api import Api
  File "C:\miniforge3\envs\main37\lib\site-packages\pyairtable\api\api.py", line 223
    if not (offset := response.get(offset_field)):
                   ^
SyntaxError: invalid syntax

Am I missing something?

Thanks in advance,
Matt

**Comment by mesozoic** [comment]
It looks like you are running Python 3.7, which [reached end-of-life in June 2023](https://devguide.python.org/versions/). If upgrading to a supported version of Python is not possible, you will need to pin your project's dependencies to the 1.x version of this library, with a version specifier like `pyairtable~=1.5` or `pyairtable>=1.5,<2.0`

**Comment by gismcieri** [comment]
Thanks so much. Can't believe I missed that. Everything is working as expected now.

Matt
