### ISSUE TITLE
LookupField referencing a LinkField returns id rather than entity

### ISSUE THREAD

**Issue by david-waterworth** [gtalarico/pyairtable#327]
I'm trying to generate a model from an existing airtable schema. I'm having trouble modelling a chain where a `LookupField` references a field in a linked table, where the referenced field is itself a `LinkField` to a third table.

i.e. in the schema below, Template.equipment_types does a lookup of the linked  `Category.equipment_types`, and this field is itself linked to `EquipmentType`

If I materialise a Category, i.e. `Category.from_id("XXX") `, the `equipment_types` field is a list of `EquipmentType`

But if I materialise a Template, `equipment_types` is a list of `str` containing EquipmentType ids and I have perform an additional request to get the actual entities.

Is this a bug, not supported or am I doing something incorrect?

```
class EquipmentType(Model):
    Name = F.TextField("Name")

class Category(Model):
    Name = F.TextField("Name")
    equipment_types = F.LinkField[EquipmentType]("equipment_types", EquipmentType)

class Template(Model):
    equipment_types = F.LookupField[EquipmentType]("equipment_types (from template_category)")
    template_category = F.LinkField[str]("template_category", Category)
```

**Comment by mesozoic** [comment]
This doesn't appear to be a bug _per se_ but I can see how the documentation doesn't make it clear what to do here. LookupField will always return the list of values it gets back from the API. Try this instead; if that also doesn't work, then we've probably got a bug:

```python
class Template(Model):
    template_category = F.LinkField[Category]("template_category", Category)
    equipment_types = F.LinkField[EquipmentType](
        field="equipment_types (from template_category)",
        model=EquipmentType,
        readonly=True
    )
```

**Comment by david-waterworth** [comment]
Thanks @mesozoic - that works!

**Comment by david-waterworth** [comment]
Just a quick follow up, as I said this works, but performance was terrible and looking at the debug messages it's doing thousands of individual GET's,

So instead I removed the `equipment_types` from `Template` and accessed indirectly via `template_category` which was orders of magnitude faster.
