### ISSUE TITLE
One to many search difficulties

### ISSUE THREAD

**Issue by Garito** [gtalarico/pyairtable#335]
Hi
I have a table with master and another with the detail
The detail records have the id of the master
How can I search for details of a particular master?
I'm using this match:
```python
match({"Série": serie, "Sub-série": subserie})
```
without success
Can you point me where am I failing?
Thanks

**Comment by mesozoic** [comment]
You should be able to search the record link field using the value that you'd see in the primary field of the linked table. In your case, if **Série** is a record link field to a table called **Series**, you'd want the `serie` variable to contain whatever value appears in the primary field of the **Series** table.

Hope that helps! I'm closing this issue as it doesn't appear to be a problem with the library. If you think you've encountered a bug in pyAirtable, please post more details and an example of how to reproduce the bug.

**Comment by Garito** [comment]
It is not a bug in pyAirtable
I've tried to look for a record in the many part and the primary key is stored as ```[value]```
Does it mean that my client has configured the field as a many-to-many relationship?
If so, can this configuration be changed without loosing data? or
How can I search it as a list of keys?
I've tried ```match({"Série": [serie]})``` but it raises an error

Thanks

**Comment by mesozoic** [comment]
That's true: Airtable will always return record link fields as a list of IDs, regardless of whether the UI is configured to allow multiple records. 

I don't think it is possible to construct a formula that searches on the list of record IDs in a linked record field. You might have more luck finding workarounds on the [Airtable Community forums](https://community.airtable.com/).
