### ISSUE TITLE
CSV import 

### ISSUE THREAD

**Issue by edoublin1111** [gtalarico/pyairtable#372]
Hi, I am going to import CSV using pyairtable.
Is it possible?

**Comment by mesozoic** [comment]
pyAirtable doesn't expose any methods for this, but you can use the [Api.request](https://pyairtable.readthedocs.io/en/stable/api.html?highlight=request#pyairtable.Api.request) method to make calls directly to the [Sync CSV Data](https://airtable.com/developers/web/api/post-sync-api-endpoint) endpoint. There are some prerequisites and constraints documented on that page.

**Comment by hdoublin** [comment]
I need to upload csv like this way,

**Comment by mesozoic** [comment]
I'd recommend asking your question on the [Airtable Community Forums](https://community.airtable.com/). This GitHub project is an independent client library specifically for Python code to connect to the Airtable API.
