### ISSUE TITLE
enterprise.info() no longer works

### ISSUE THREAD

**Issue by buckbanzai** [gtalarico/pyairtable#404]
With the API changes made today to the Enterprise API, the `enterprise.info()` function no longer works, since the `include` options have been changed in a backward incompatible way: https://airtable.com/developers/web/api/get-enterprise

Changelog: https://airtable.com/developers/web/api/changelog#anchor-2024-11-11

**Comment by mesozoic** [comment]
Yikes! Thanks for the bug report. I actually don't think the `include=` params were ever used, so I think it was a "quiet bug" that we were ever passing them in the first place. I'll hotfix now.

**Comment by mesozoic** [comment]
OK, a fix for this has been released as 2.3.6. Thanks again for the bug report. I'll have to pick up the rest of the changes they announced another day.

**Comment by buckbanzai** [comment]
Thanks so much for the quick fix!
