### ISSUE TITLE
Can't find a way to get the workspace id

### ISSUE THREAD

**Issue by matteo-rusconi** [gtalarico/pyairtable#409]
According to docs, workspace id is required for creating new bases:

`Api.create_base(workspace_id, name, tables)`

but i can't find any method to get the that id, and the Airtable UI doesn't show it neither.

**Comment by gtalarico** [comment]
Have you tried the steps from this doc 👇🏼 @matteo-rusconi ?
https://support.airtable.com/docs/finding-airtable-ids

**Comment by matteo-rusconi** [comment]
Yep, my bad. I found it right after i opened the issue. Thanks.
