### ISSUE TITLE
create_table From Model Definition

### ISSUE THREAD

**Issue by liko28s** [gtalarico/pyairtable#418]
Hi guys, I'm just trying to create a new table based on Model class Schema, what I'm doing is getting fields from `_field_name_descriptor_map` but it doesn't work.

base.create_table("TABLE NAME", fields=TableModel._field_name_descriptor_map()

But the __repr__ of fields in the returned value doesn't match requirements for table creation.

Any help is appreciated

**Comment by mesozoic** [comment]
The fields parameter needs to be a list of `dict` objects that conform to the format specified in Airtable's [field types reference](https://airtable.com/developers/web/api/field-model). You can see an example in the API documentation for the [Create table endpoint](https://airtable.com/developers/web/api/create-table).

Right now there's no out-of-the-box way to generate those kinds of objects from an ORM model. You can generate something like them through the table metadata, but it will likely include some read-only properties that the endpoint won't accept. Here's a starting point:

```python
>>> field_schemas = [
...     TableModel.meta.table.schema().field(name).model_dump()
...     for name in TableModel._field_name_descriptor_map()
... ]

>>> field_schemas
[
    {'type': 'singleLineText', 'id': 'fldjMJMBjUbn6XFRL', 'name': 'Name', 'description': None},
    {'type': 'multilineText', 'id': 'fldisWnZGrxzMsxKk', 'name': 'Notes', 'description': None},
    ...
]
```
