### ISSUE TITLE
Error - INVALID_ATTACHMENT_OBJECT

### ISSUE THREAD

**Issue by Sree-NJ** [gtalarico/pyairtable#74]
Hi 
I am getting an error like this, i am trying to attach a URL pulled from google cloud. 

HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.airtable.com/v0/appgg2Dz6pmuRMwiQ/PO/recXVxnFpSBlYCqzw (Decoded URL) [Error: {'type': 'INVALID_ATTACHMENT_OBJECT', 'message': 'Invalid attachment for field Invoice PDF: parameters must be objects, not strings'}]

Please help, 
Thanks,Sree

**Comment by gtalarico** [comment]
You might want to check or post this on airtable community forum
https://community.airtable.com/c/developers/api/6

If you find the cause please post back.

Are you including a public accessible url?
You want to review:
* https://chinarajames.com/how-to-upload-images-to-airtable-using-their-api/
* https://community.airtable.com/t/is-it-possible-to-upload-attachments/188/22

**Comment by edsu** [comment]
I had the same problem I was trying to update a column called 'headshot' that contains an image attachment. You need to be sure to pass in a list of dictionaries where the dictionary has a key 'url' whose value is the url for your file. Here's an example:

```python
table.update(rec_id, {'headshot': [{'url': headshot_url}]})
```

**Comment by nandodrw** [comment]
thanks @edsu your answers solved the problem for me.

**Comment by eoglethorpe** [comment]
@edsu you're a gentleman and a scholar

**Comment by gtalarico** [comment]
Thanks @edsu leaving this here for reference.
Might good to do a FAQ on docs on issues like.
If anyone is interesting on contributing to a FAQ feel free to PR

**Comment by gtalarico** [comment]
https://github.com/gtalarico/pyairtable/pull/130
