### ISSUE TITLE
Base ID or Application Record IDs

### ISSUE THREAD

**Issue by KalobTaulien** [gtalarico/pyairtable#84]
I'm looking for a way to link directly to an Airtable record (inside the app, not the API url). So far no luck finding it. 

Ideally I think a record url would easier than trying to collect the Base ID and the View ID and appending the recordId to those. 

I think this could be done creatively with the Airtable Enterprise API, but there _must_ be a way to generate this simple URL using their existing API.

Perhaps this exists already.. if it does feel free to close this issue.

**Comment by ezeagwulae** [comment]
Every record has unique record id which is returned on every API call or from your view you can retrieve the `RECORD_ID()` formula. have you explored that or are you after something else?

using this output as an example, Airtable returns an `id` field something like this:

```
[
    {
        "id": "att6f75cc83f1b648",
        "size": 26317,
        "url": "https://www.filepicker.io/api/file/5YTJXioCQG0tYWPw6OPw",
        "type": "image/jpeg",
        "filename": "33823_3_xl.jpg",
        "thumbnails": {
            "small": {
                 "url": "https://www.filepicker.io/api/file/Dy5gioxaShSUvHX0LgIC",
                 "width": 54,
                 "height": 36
             },
            "large": {
                 "url": "https://www.filepicker.io/api/file/ueYi00yRiqhuUn420UZA",
                 "width": 197,
                 "height": 131
             }
         }
    }
]
```

**Comment by KalobTaulien** [comment]
Mmm not quite. I'm looking more for the ability to link to an expanded record on airtable.com. Like this url:

```
https://airtable.com/tblUPdzGYuIB4G4us/viwtBlC28GBxQYLBg/recyVbtJNqJ4j9qGc
                           ^ That         and ^ that 
```
Is there a programatic way to get those, or a way to get this entire url?

**Comment by ezeagwulae** [comment]
The RECORD_ID is the same as the expanded link. Programmatically you can get it this way

```
    from airtable import Airtable
    airtable = Airtable(base_key="BASE_KEY", table_name="TABLE_ID",
                        api_key="API_KEY")
    airtableViewId = "viwjHyYDmppGlIi6r"
    AIRTABLE_URL = "https://airtable.com/" + airtable.table_name + "/" + airtableViewId + "/"
    allRecords = airtable.get_all(view=airtableViewId)
    allLinkedRecords = [AIRTABLE_URL + i['id'] for i in allRecords]
    print(allLinkedRecords)
``` 

you definitely simplify or pretty the logic but that returns a list of expanded url's in that view

**Comment by gtalarico** [comment]
This is now possible using meta api - might consider adding this one meta api is implemented in client

**Comment by gtalarico** [comment]
Should be able to do this using metadata api, however not counting on this since Metadata seems to be lacking support (e.g. they are not adding new users to it, only Enterprise API).
If you have been granted metadata access you should be able to get view id:
https://pyairtable.readthedocs.io/en/latest/metadata.html

This is def. a nice feature to have but I think we are able to deliver it without a stable, accessible metadata api.
Feel free to continue to discussion but will close this to keep open issues to only actionable items
